# Generated by Django 3.0 on 2020-03-12 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_user_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('date1', models.DateTimeField(auto_now=True, null=True)),
                ('date2', models.DateTimeField(auto_now_add=True, null=True)),
                ('img', models.ImageField(null=True, upload_to='img')),
            ],
        ),
    ]
